LOSS_DELTA_CONVERGED_THRESHOLD = 0.05
LOSS_DIFF_THRESHOLD = 0.05

WARM_UP_ROUNDS = 15


# transmission bandwidth
MIN_UPLOAD_BANDWIDTH = 10
MAX_UPLOAD_BANDWIDTH = 40

MIN_DOWNLOAD_BANDWIDTH = 100
MAX_DOWNLOAD_BANDWIDTH = 300